env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 13
rules:
  max-len: off
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
